Evaluate a policy given an environment and a full description of the environment's dynamics.
    
    Args:
        policy: [S, A] shaped matrix representing the policy.
        env: OpenAI env. env.P represents the transition probabilities of the environment.
            env.P[s][a] is a list of transition tuples (prob, next_state, reward, done).
            env.nS is a number of states in the environment. 
            env.nA is a number of actions in the environment.
        theta: We stop evaluation once our value function change is less than theta for all states.
        discount_factor: Gamma discount factor.
    
    Returns:
        Vector of length env.nS representing the value function.

In [19]:
from IPython.core.debugger import set_trace
import numpy as np
import pprint
import sys
if "../" not in sys.path:
  sys.path.append("../") 
from lib.envs.gridworld import GridworldEnv

In [20]:
pp = pprint.PrettyPrinter(indent=2)
env = GridworldEnv()

In [26]:
def policy_eval(policy, env, discount_factor=1.0, theta=0.00001):
    
    # Start with a random value function (All 0)
    V = np.zeros(env.nS)
    
    while True:
        delta = 0
        # Full backup for for each state
        for s in range(env.nS):
            v = 0
            # Possible next actions
            for a, action_prob in enumerate(policy[s]):
                # Possible next states for each action
                for  prob, next_state, reward, done in env.P[s][a]:
                    # Expected value
                    v += action_prob * prob * (reward + discount_factor * V[next_state])
            # Change in value function
            delta = max(delta, np.abs(v - V[s]))
            V[s] = v
        # Stop evaluating once value function changes below threshold
        if delta < theta:
            break
    return np.array(V)

In [27]:
random_policy = np.ones([env.nS, env.nA]) / env.nA
v = policy_eval(random_policy, env)

In [29]:
print("Value function:")
print(v)

Value function:
[  0.         -13.99993529 -19.99990698 -21.99989761 -13.99993529
 -17.9999206  -19.99991379 -19.99991477 -19.99990698 -19.99991379
 -17.99992725 -13.99994569 -21.99989761 -19.99991477 -13.99994569
   0.        ]


In [33]:
print("Grid Value Function")
print(v.reshape(env.shape))

Grid Value Function
[[  0.         -13.99993529 -19.99990698 -21.99989761]
 [-13.99993529 -17.9999206  -19.99991379 -19.99991477]
 [-19.99990698 -19.99991379 -17.99992725 -13.99994569]
 [-21.99989761 -19.99991477 -13.99994569   0.        ]]
