In [17]:
import numpy as np
import gym
import random
import time
from IPython.display import clear_output

In [18]:
env = gym.make("FrozenLake-v0")

In [19]:
state_space_size = env.observation_space.n
action_space_size = env.action_space.n

#Creating a q-table and intialising all values as 0
q_table = np.zeros((state_space_size,action_space_size))
print(q_table)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [20]:
#Number of episodes
num_episodes = 1000
#Max number of steps per episode
max_steps_per_episode = 100

learning_rate = 0.1
discount_rate = 0.99

#Greedy strategy
exploration_rate = 1
max_exploration_rate = 1
min_exploration_rate = 0.01
exploration_decay_rate = 0.01

In [21]:
rewards_all_episodes = [] #List to contain all the rewards of all the episodes given to the agent
#Q-Learning Algorithm

for episode in range(num_episodes): #Contains that happens in an episode
    state = env.reset()
    
    done = False #Tells us whether episode is finished
    rewards_current_episode = 0
    
    for step in range(max_steps_per_episode): #Contains that happens in a time step
        
        #Exploration-exploitation trade off
        exploration_rate_threshold = random.uniform(0,1)
        
        if exploration_rate_threshold > exploration_rate:
            action = np.argmax(q_table[state,:])
        else:
            action = env.action_space.sample()
            
        new_state, reward, done, info = env.step(action)
        
        #Update Q-table for Q(s,a)
        q_table[state, action] = q_table[state, action] * (1 - learning_rate) + \
            learning_rate * (reward + discount_rate * np.max(q_table[new_state, :]))
        
        state = new_state
        rewards_current_episode += reward
        
        if done == True: #Checking if episode is over
            break
            
    # Exploration rate decay
    exploration_rate = min_exploration_rate + \
        (max_exploration_rate - min_exploration_rate) * np.exp(-exploration_decay_rate*episode)
    
    rewards_all_episodes.append(rewards_current_episode)
    
# Calculate and print the average reward per thousand episodes
rewards_per_thousand_episodes = np.split(np.array(rewards_all_episodes),num_episodes/1000)
count = 1000

print("********Average reward per thousand episodes********\n")
for r in rewards_per_thousand_episodes:
    print(count, ": ", str(sum(r/1000)))
    count += 1000

#Print the updates Q-Table
print("\n\n*******Q-Table*******\n")
print(q_table)

********Average reward per thousand episodes********

1000 :  0.1540000000000001


*******Q-Table*******

[[0.06245426 0.12670584 0.23880228 0.10889446]
 [0.05624363 0.07058303 0.06794457 0.20343652]
 [0.11001466 0.20282837 0.06914879 0.04703144]
 [0.06728941 0.08421008 0.03096355 0.18503696]
 [0.26132055 0.05526237 0.06611129 0.06621492]
 [0.         0.         0.         0.        ]
 [0.06637221 0.04992502 0.2415197  0.01616846]
 [0.         0.         0.         0.        ]
 [0.04940704 0.07051077 0.07902728 0.3023673 ]
 [0.10870343 0.38047173 0.13174995 0.0122077 ]
 [0.46862546 0.08710869 0.01312738 0.01541129]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.02260822 0.11899161 0.15647675 0.33823676]
 [0.06153008 0.33621631 0.69578064 0.20231125]
 [0.         0.         0.         0.        ]]


In [24]:
# Watch our agent play Frozen Lake by playing the best action 
# from each state according to the Q-table

for episode in range(5):
    # initialize new episode params
    state = env.reset()
    done = False
    print("*******Episode ", episode+1, "*******\n\n\n\n")
    time.sleep(1)
    for step in range(max_steps_per_episode):        
        # Show current state of environment on screen
        clear_output(wait=True)
        # Choose action with highest Q-value for current state
        env.render()
        # Take new action
        time.sleep(0.3)
        
        action = np.argmax(q_table[state,:])
        new_state, reward, done, info = env.step(action)
        if done:
            clear_output(wait=True)
            env.render()
            if reward == 1:
                # Agent reached the goal and won episode
                print("****You reached the goal****")
                time.sleep(3)
            else:
                # Agent stepped in a hole and lost episode  
                print("****You lost****")
                time.sleep(3)
            clear_output(wait=True)
            break
        # Set new state
        state = new_state
        
env.close()

  (Right)
SFFF
FHFH
FFFH
HFFG
****You lost****
